language: ruby
sudo: false

cache: bundler

rvm:
 - 2.5.1

bundler_args: --without production

install:
  - bundle install

services:
  - postgresql

before_script:
  - psql -c 'create database "tumblr-tags_test";' -U postgres

test:
  adapter: postgresql
  database: tumblr-tags_test
